language: minimal
dist: xenial

install: true

script:
  - cd ci && make docker_ubuntu
  - cd ci && make configure_ubuntu
  - cd ci && make build_ubuntu
  - cd ci && make test_ubuntu
  - cd ci && make install_ubuntu
  - cd ci && make test_install_ubuntu
