language: minimal
dist: xenial

install: true

script:
  - cd ci
  - make docker_ubuntu
  - make configure_ubuntu
  - make build_ubuntu
  - make test_ubuntu
  - make install_ubuntu
  - make test_install_ubuntu
