sudo: required
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      compiler: g++-6
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - cmake -H. -Bbuild -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build build --target all
  - cmake --build build --target test
