language: minimal
dist: xenial

matrix:
  include:
    - env: DISTRO=alpine
    - env: DISTRO=ubuntu

install: true

script:
  - cd ci
  - make docker_${DISTRO}
  - make configure_${DISTRO}
  - make build_${DISTRO}
  - make test_${DISTRO}
  - make install_${DISTRO}
  - make test_install_${DISTRO}
