language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc

    - os: linux
      dist: xenial
      compiler: clang

    - os: osx
      osx_image: xcode10.1
      compiler: clang



before_install:
  - eval "${MATRIX_EVAL}"

install: true

script:
  - cmake --version
  - cmake -H. -Bbuild -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build build --target all
  - cmake --build build --target install
#  - cmake --build build --target test
